version: '3.8'

services:
  moodle:
    image: moodlehq/moodle
    container_name: moodle
    restart: always
    ports:
      - "8080:80"
    environment:
      - MOODLE_DATABASE_TYPE=mariadb
      - MOODLE_DATABASE_HOST=db
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=moodlepassword
      - MOODLE_DATABASE_NAME=moodle
    volumes:
      - moodledata:/var/www/moodledata
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: moodle-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=moodlepassword
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  moodledata:
  dbdata:
